"""
Step 5 of 5: the data-driven tables of the paper as LaTeX.

Everything is read from the input data (data/) or from the outputs of
run_paper_analysis.py and compute_network_value.py; no numbers are typed in
by hand. Tables are written to outputs/tables/.

Tables
------
table_archetypes.tex       Building archetypes (q_SH, FED, stock weight, baseline RT)
table_measures.tex         Measure characteristics with data-source column
table_main_results.tex     Choice shares, diffusion-adjusted stock adoption,
                           network value and owner cost change
table_nested_logit.tex     Nested-logit robustness summary
(The economic-parameter table carries citations and is written in the paper.)

Run:  python make_tables.py
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

from load_data import load_all_measures, load_building_baseline_rt, MEASURE_SHORT_NAMES
from load_invert_data import load_renovation_data

ROOT = Path(__file__).resolve().parent
OUT = ROOT / 'outputs' / 'tables'
PAPER = ROOT / 'outputs' / 'paper_analysis'

ARCHETYPE_ORDER = ['1919_TOP 6', '1919_TOP 12', '1919_TOP 24',
                   '1960_TOP 6', '1960_TOP12', '1960_TOP 24',
                   '2001_TOP 6', '2001_TOP 12', '2001_TOP 24']

ALL_IDS = ['1.3', '1.5', '2.1', '2.3', '2.5', '2.7', '2.8', '2.9', '2.10', 'baseline']

ROW_LABELS = {
    '1.3': 'M1 Flow limiter',
    '1.5': 'M2 Heat exchanger',
    '2.1': 'M3 Hydraulic balancing',
    '2.3': 'M4 Pump downsizing',
    '2.5': 'M5 Buffer storage',
    '2.7': 'M6 User behavior',
    '2.8': 'M7 Pump + flow limiter',
    '2.9': 'M8 Pump + flow + balancing',
    '2.10': 'M9 Balancing + heat exchanger',
    'baseline': 'Do nothing',
}

# Data source per measure (see the paper, Section 4.2)
PROVENANCE = {
    '1.3': 'Simulated',
    '1.5': 'Simulated',
    '2.1': 'Simulated',
    '2.3': 'Simulated, neg.\\ $\\Delta T_{\\mathrm{RT}}$',
    '2.5': 'Assumed, lit.\\ costs',
    '2.7': 'Expert guess, $\\eta$ assumed',
    '2.8': 'Simulated',
    '2.9': 'Simulated',
    '2.10': 'Simulated',
}


def esc(s):
    return str(s).replace('_', '\\_').replace('%', '\\%').replace('&', '\\&')


def display_name(bt):
    """Normalize raw archetype keys for display ('1960_TOP12' -> '1960_TOP 12')."""
    return bt.replace('TOP12', 'TOP 12')


def fmt_range(arr, decimals=1, thousands=False):
    lo, hi = float(np.min(arr)), float(np.max(arr))
    def f(x):
        if thousands:
            return f"{x:,.0f}"
        return f"{x:.{decimals}f}"
    if abs(hi - lo) < 10 ** (-decimals) / 2:
        return f"${f(lo)}$" if lo < 0 else f(lo)
    if lo < 0:
        # math-mode minus signs; '--' after a minus would render as an em dash
        return f"${f(lo)}$ to ${f(hi)}$"
    return f"{f(lo)}--{f(hi)}"


def write(path, content):
    path.write_text(content, encoding='utf-8')
    print(f"[OK] {path}")


# -----------------------------------------------------------------------------
# Building archetypes
# -----------------------------------------------------------------------------

def table_archetypes():
    all_measures = load_all_measures()
    first = next(iter(all_measures.values()))
    reno = load_renovation_data(year=2030, archetype_types=first['building_types'])
    baseline_rts = load_building_baseline_rt()

    rows = []
    for bt in ARCHETYPE_ORDER:
        cls = reno['building_classes'][bt]
        no_action = next(v for v in cls['variants'] if v['action'] == 'no action')
        stock = sum(v['number_of_buildings'] for v in cls['variants'])
        period, size = bt.split('_')
        dwellings = size.replace('TOP', '').strip()
        rt = baseline_rts.get(bt, float('nan'))
        rows.append(
            f"{esc(display_name(bt))} & {'pre-1919' if period == '1919' else period} & {dwellings} & "
            f"{no_action['hwb_norm']:.0f} & {no_action['fed_sh_per_bssh'] / 1000.0:.1f} & "
            f"{stock:.0f} & {rt:.1f} \\\\")

    content = (
        "% Generated by make_tables.py\n"
        "% src: data/building_measures.xlsx + data/invert_building_stock_2030.csv\n"
        "\\begin{table}[htbp]\n\\centering\n"
        "\\caption{Building archetypes of the Austrian multi-family case study. "
        "The specific space-heating demand $\\qsh$ and the final energy demand (FED) refer to the "
        "unrenovated (no-action) state in the 2030 "
        "building-stock scenario. The weight is the number of buildings in the modeled Invert building "
        "stock, summed across all renovation states, and sets the relative importance of each archetype in "
        "the aggregation. The baseline return temperature $\\Trtb$ is the annual mean from the building simulations.}\n"
        "\\label{tab:archetypes}\n"
        "\\footnotesize\n"
        "\\setlength{\\tabcolsep}{3.5pt}\n"
        "\\begin{tabular}{llccccc}\n\\toprule\n"
        "Archetype & Period & Dwellings & $\\qsh$ & FED & Weight & $\\Trtb$ \\\\\n"
        " & & & (kWh\\,m$^{-2}$\\,a$^{-1}$) & (MWh\\,a$^{-1}$) & (buildings) & ($^{\\circ}$C) \\\\\n"
        "\\midrule\n" + "\n".join(rows) + "\n"
        "\\bottomrule\n\\end{tabular}\n\\end{table}\n")
    write(OUT / 'table_archetypes.tex', content)


# -----------------------------------------------------------------------------
# Measure characteristics with data source
# -----------------------------------------------------------------------------

def table_measures():
    all_measures = load_all_measures()
    rows = []
    for mid in [m for m in ALL_IDS if m != 'baseline']:
        d = all_measures[mid]
        rows.append(
            f"{ROW_LABELS[mid]} & "
            f"{fmt_range(np.asarray(d['investment_costs']) / 1000.0, 1)} & "
            f"{fmt_range(d['lifetimes'], 0)} & "
            f"{fmt_range(d['efficiency_improvement'], 1)} & "
            f"{fmt_range(d['rt_reduction'], 2)} & "
            f"{PROVENANCE[mid]} \\\\")

    content = (
        "% Generated by make_tables.py\n"
        "% src: data/building_measures.xlsx (ranges across the 9 archetypes)\n"
        "\\begin{table*}[htbp]\n\\centering\n"
        "\\caption{Characteristics of the nine building-side measures. Ranges span the nine "
        "archetypes. The last column distinguishes parameters obtained from the "
        "building-specific coupled simulations (``simulated'') from assumption-based "
        "values. See \\cref{sec:data:measures} for discussion.}\n"
        "\\label{tab:measures}\n"
        "\\footnotesize\n"
        "\\begin{tabularx}{\\textwidth}{Xcccc>{\\raggedright\\arraybackslash}p{2.4cm}}\n\\toprule\n"
        "Measure & Investment & Lifetime & Efficiency & $\\Delta T_{\\mathrm{RT}}$ & Data source \\\\\n"
        " & (kEUR) & (a) & (\\%) & (K) & \\\\\n"
        "\\midrule\n" + "\n".join(rows) + "\n"
        "\\bottomrule\n\\end{tabularx}\n\\end{table*}\n")
    write(OUT / 'table_measures.tex', content)


# -----------------------------------------------------------------------------
# Main results (choice shares, diffusion-adjusted adoption, network value)
# -----------------------------------------------------------------------------

def money(x):
    sign = '$-$' if x < 0 else '+'
    return f"{sign}{abs(x):,.0f}"


def table_main_results():
    df = pd.read_csv(PAPER / 'base_case' / 'overall_shares_with_diffusion.csv')
    nv = pd.read_csv(PAPER / 'base_case' / 'network_value_2030.csv',
                     dtype={'measure_id': str}).set_index('measure_id')
    piv_choice = df.pivot(index='measure_id', columns='year', values='choice_share')
    piv_stock = df.pivot(index='measure_id', columns='year', values='stock_adoption')

    rows = []
    for mid in ALL_IDS:
        if mid == 'baseline':
            tail = "0.0 & --- & ---"
        else:
            d_rt = nv.loc[mid, 'd_rt_K']
            lo, hi = nv.loc[mid, 'v_net_mid_EUR'], nv.loc[mid, 'v_net_high_EUR']
            if abs(hi) < 1.0:
                val = "$<$1"
            elif lo < 0:
                val = f"$-${abs(lo):.0f} to $-${abs(hi):.0f}"
            else:
                val = f"{lo:.0f}--{hi:.0f}"
            d_rt_s = f"{d_rt:.1f}".replace('-', '$-$')
            tail = f"{d_rt_s} & {val} & {money(nv.loc[mid, 'net_cost_change_EUR'])}"
        rows.append(
            f"{ROW_LABELS[mid]} & "
            f"{piv_choice.loc[mid, 2030] * 100:.1f} & {piv_choice.loc[mid, 2040] * 100:.1f} & "
            f"{piv_stock.loc[mid, 2030] * 100:.1f} & {piv_stock.loc[mid, 2040] * 100:.1f} & "
            f"{tail} \\\\")

    content = (
        "% Generated by make_tables.py\n"
        "% src: outputs/paper_analysis/base_case/overall_shares_with_diffusion.csv,\n"
        "%      outputs/paper_analysis/base_case/network_value_2030.csv\n"
        "\\begin{table*}[htbp]\n\\centering\n"
        "\\caption{Stock-weighted results for the reference scenario (no tariff, no subsidy, "
        "$\\lambda=4$, 0.10\\,EUR\\,kWh$^{-1}$). Choice shares are conditional on a decision "
        "occasion. Stock adoption applies $d_{2030}=20\\,\\%$ and $d_{2040}=60\\,\\%$ and counts "
        "the remaining stock as do-nothing. Last three columns (2030, per building): "
        "$\\Delta T_{\\mathrm{RT}}$, network value at gradients of 0.12 and "
        "0.67\\,EUR\\,MWh$^{-1}$\\,K$^{-1}$ (Eq.~3), and change in the owner's total annual "
        "heating cost relative to do-nothing (Eq.~1).}\n"
        "\\label{tab:mainresults}\n"
        "\\footnotesize\n"
        "\\setlength{\\tabcolsep}{4pt}\n"
        "\\begin{tabular}{lcccccrr}\n\\toprule\n"
        " & \\multicolumn{2}{c}{Choice share (\\%)} & \\multicolumn{2}{c}{Stock adoption (\\%)} "
        "& $\\Delta T_{\\mathrm{RT}}$ & Network value & Owner cost change \\\\\n"
        "\\cmidrule(lr){2-3}\\cmidrule(lr){4-5}\n"
        "Alternative & 2030 & 2040 & 2030 & 2040 & (K) & (EUR\\,a$^{-1}$) & (EUR\\,a$^{-1}$) \\\\\n"
        "\\midrule\n" + "\n".join(rows) + "\n"
        "\\bottomrule\n\\end{tabular}\n\\end{table*}\n")
    write(OUT / 'table_main_results.tex', content)


# -----------------------------------------------------------------------------
# Nested-logit robustness
# -----------------------------------------------------------------------------

def table_nested_logit():
    df = pd.read_csv(PAPER / 'nested_logit' / 'nl_robustness.csv')
    df = df[df['year'] == 2030]

    partition_labels = {'A': 'Choice structure', 'B': 'Component family'}
    rows = []
    for pname in ('A', 'B'):
        for theta in (1.0, 0.7, 0.5, 0.3):
            sub = df[(df['partition'] == pname) & (df['theta'] == theta)]
            top = sub.sort_values('rank').head(3)
            top_str = ', '.join(
                ROW_LABELS[m].split(' ')[0] if m != 'baseline' else 'DN'
                for m in top['measure_id'])
            dn = float(sub.loc[sub['measure_id'] == 'baseline',
                               'stock_weighted_share'].iloc[0]) * 100
            mx = float(sub['delta_pp'].abs().max())
            label = ('MNL ($\\theta=1$)' if theta == 1.0 else f"$\\theta={theta}$")
            cell = partition_labels[pname] if theta == 1.0 else ''
            rows.append(f"{cell} & {label} & {top_str} & {dn:.1f} & {mx:.1f} \\\\")

    content = (
        "% Generated by make_tables.py\n"
        "% src: outputs/paper_analysis/nested_logit/nl_robustness.csv\n"
        "\\begin{table}[htbp]\n\\centering\n"
        "\\caption{Nested-logit robustness check (reference scenario, 2030). The choice-structure "
        "partition nests do-nothing / single measures / combinations, and the component-family "
        "partition nests by "
        "dominant component family. Lower $\\theta$ means stronger within-nest substitution. "
        "$\\theta=1$ reproduces the multinomial logit. The last column reports the largest "
        "absolute change of any alternative's stock-weighted share relative to the MNL.}\n"
        "\\label{tab:nl}\n"
        "\\small\n"
        "\\begin{tabular}{lllcc}\n\\toprule\n"
        "Partition & Model & Top-3 alternatives & Do-nothing (\\%) & max $|\\Delta|$ (pp) \\\\\n"
        "\\midrule\n" + "\n".join(rows) + "\n"
        "\\bottomrule\n\\end{tabular}\n\\end{table}\n")
    write(OUT / 'table_nested_logit.tex', content)


if __name__ == '__main__':
    OUT.mkdir(parents=True, exist_ok=True)
    table_archetypes()
    table_measures()
    table_main_results()
    table_nested_logit()
    print("\nAll tables written to outputs/tables/")
